# Generated by Django 2.1.7 on 2019-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0002_auto_20190520_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(help_text='Введите варианты ответов через , ', max_length=500, null=True, verbose_name='Варианты ответов (вводить через ",")'),
        ),
    ]
