# Generated by Django 2.1.7 on 2019-05-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0003_auto_20190520_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learn_app.Course'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(verbose_name='Срок сдачи (в формате "01/29/19")'),
        ),
    ]
