# Generated by Django 2.1.7 on 2019-05-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0005_remove_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learn_app.Question'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
