# Generated by Django 2.1.7 on 2019-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0006_auto_20190511_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
